release:
  github:
    owner: ekristen
    name: cloud-provider-zero
  prerelease: auto
builds:
  - id: cloud-provider-zero
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
archives:
  - id: cloud-provider-zero
    builds:
      - cloud-provider-zero
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - id: cloud-provider-zero-amd64
    ids:
      - cloud-provider-zero
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ekristen/cloud-provider-zero:v{{ .Version }}-amd64
      - ghcr.io/ekristen/cloud-provider-zero:{{ replace .Branch "/" "-" }}-{{ .ShortCommit }}-{{ .Timestamp }}-amd64
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{replace (replace (replace .GitURL \"git@\" \"https://\") \".git\" \"\") \"github.com:\" \"github.com/\"}}"
      - "--platform=linux/amd64"
  - id: cloud-provider-zero-arm64
    ids:
      - cloud-provider-zero
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ekristen/cloud-provider-zero:v{{ .Version }}-arm64
      - ghcr.io/ekristen/cloud-provider-zero:{{ replace .Branch "/" "-" }}-{{ .ShortCommit }}-{{ .Timestamp }}-arm64
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{replace (replace (replace .GitURL \"git@\" \"https://\") \".git\" \"\") \"github.com:\" \"github.com/\"}}"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "ghcr.io/ekristen/cloud-provider-zero:v{{ .Version }}"
    image_templates:
      - "ghcr.io/ekristen/cloud-provider-zero:v{{ .Version }}-amd64"
      - "ghcr.io/ekristen/cloud-provider-zero:v{{ .Version }}-arm64"
signs:
  - cmd: cosign # Sign with Password
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args: ["sign-blob", "--yes", "--tlog-upload=false", "--key=cosign.key", "--output-signature=${signature}", "${artifact}"]
    artifacts: all
  #- ids:
  #    - template
  #  cmd: cosign
  #  signature: "${artifact}.sig"
  #  certificate: "${artifact}.pem"
  #  args: ["sign-blob", "--yes", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-certificate=${certificate}", "--output-signature=${signature}", "${artifact}"]
  #  artifacts: all
docker_signs:
  - ids: # Sign With Password
      - cloud-provider-zero
    artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
  #- ids:
  #    - template
  #  artifacts: all
  #  cmd: cosign
  #  args: ["sign", "--yes", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-certificate=${certificate}", "--output-signature=${signature}", "${artifact}"]
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
