apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-provider-zero-webhook
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
