apiVersion: v1
kind: Service
metadata:
  name: odin-webhook
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
      name: http
  selector:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
    component: webhook-server