name: release-chart
on:
  push:
    tags:
      - 'chart-*'
  workflow_dispatch:

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.EKRISTEN_HELM_CHARTS_GITHUB_TOKEN }}
          charts_dir: chart
          charts_url: https://ekristen.github.io/helm-charts/
          owner: ekristen
          repository: helm-charts
          branch: gh-pages
          commit_username: ekristen
          commit_email: erik@erikkristensen.com