name: release-chart
on:
  push:
    tags:
      - 'chart-*'
  workflow_dispatch:

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ekristen
          password: ${{ secrets.EKRISTEN_HELM_CHARTS_GITHUB_TOKEN }}
      - run: |
          helm package chart
          helm push $(ls *.tgz | head -n1) oci://ghcr.io/ekristen/helm-charts