name: release-chart
on:
  push:
    tags:
      - 'chart-*'
  workflow_dispatch:

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: cloud-provider-zero
          repository: ekristen/helm-charts
          tag: 0.1.0
          path: charts/my-chart # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false